Aqui, abordaremos diferentes casos de uso de como detectar duplicatas em seus dados para que sejam adequados para uma tarefa de aprendizado de máquina. Em particular, iremos abordar como usar Pandas para manipular valores quando necessário e aprender como fazer agregação em Pandas

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('breast_cancer_data.csv')
df

,patient_id,clump_thickness,cell_size_uniformity,cell_shape_uniformity,marginal_adhesion,single_ep_cell_size,bare_nuclei,bland_chromatin,normal_nucleoli,mitoses,class,doctor_name
0,1000025,5.0,1.0,1,1,2,1,3.0,1.0,1,benign,Dr. Doe
1,1002945,5.0,4.0,4,5,7,10,3.0,2.0,1,benign,Dr. Smith
2,1015425,3.0,1.0,1,1,2,2,3.0,1.0,1,benign,Dr. Lee
3,1016277,6.0,8.0,8,1,3,4,3.0,7.0,1,benign,Dr. Smith
4,1017023,4.0,1.0,1,3,2,1,3.0,1.0,1,benign,Dr. Wong
...,...,...,...,...,...,...,...,...,...,...,...,...
694,776715,3.0,1.0,1,1,3,2,1.0,1.0,1,benign,Dr. Lee
695,841769,2.0,1.0,1,1,2,1,1.0,1.0,1,benign,Dr. Smith
696,888820,5.0,10.0,10,3,7,3,8.0,10.0,2,malignant,Dr. Lee
697,897471,4.0,8.0,6,4,3,4,10.0,6.0,1,malignant,Dr. Lee
698,897471,4.0,8.0,8,5,4,5,10.0,4.0,1,malignant,Dr. Wong

Nos dados, temos as seguintes colunas, conforme descrito por [fonte] (https://archive.ics.uci.edu/ml/datasets/breast+cancer+wis Wisconsin+ (original))
- ID do paciente: número de id
- Espessura do aglomerado: 1-10
- Uniformidade do tamanho da célula: 1-10
- Uniformidade da forma celular: 1-10
- Adesão marginal: 1-10
- Tamanho de célula epitelial única: 1–10
- Núcleos nus: 1-10
- Cromatina Suave: 1-10
- Nucléolos normais: 1-10
- Mitoses: 1-10
- Classe: maligno ou benigno
- Nome do médico: 4 médicos diferentes.

#### 1. Cheque o tipo de dado de cada variável

In [3]:
df.dtypes

patient_id                 int64
clump_thickness          float64
cell_size_uniformity     float64
cell_shape_uniformity      int64
marginal_adhesion          int64
single_ep_cell_size        int64
bare_nuclei               object
bland_chromatin          float64
normal_nucleoli          float64
mitoses                    int64
class                     object
doctor_name               object
dtype: object

#### 2. Cheque quantos dados faltantes temos em cada coluna

In [4]:
df.isna().sum()

patient_id               0
clump_thickness          1
cell_size_uniformity     1
cell_shape_uniformity    0
marginal_adhesion        0
single_ep_cell_size      0
bare_nuclei              2
bland_chromatin          4
normal_nucleoli          1
mitoses                  0
class                    0
doctor_name              0
dtype: int64

Nesse caso, como temos um conjunto de dados grande o suficiente e a precisão é de extrema importância, vamos apenas descartar as colunas que contêm os valores NaN.

Tenha em mente que este ainda pode não ser o caso ideal, parte do processo de Ciência de Dados é tomar uma decisão e seguir em frente sabendo que você terá que voltar e mudar isso.

#### 3. Jogue fora os dados ausentes

In [5]:
df.dropna(axis = 0, how = 'any', inplace=True)

#### 4. Use a função `duplicated()` para checar quais são os dados duplicados

In [6]:
df[df.duplicated(keep=False)]

,patient_id,clump_thickness,cell_size_uniformity,cell_shape_uniformity,marginal_adhesion,single_ep_cell_size,bare_nuclei,bland_chromatin,normal_nucleoli,mitoses,class,doctor_name
168,1198641,3.0,1.0,1,1,2,1,3.0,1.0,1,benign,Dr. Lee
258,1198641,3.0,1.0,1,1,2,1,3.0,1.0,1,benign,Dr. Lee

Agora que lidamos com linhas inteiras que foram duplicadas, também precisamos lidar com pacientes duplicados. Lembre-se, se estivermos usando um modelo de ML para isso, precisamos nos certificar de que nenhum paciente seja repetido mais do que a média de vezes que um paciente é repetido, para que nosso modelo de ML não seja tendencioso.

Mesmo que você não entenda esse raciocínio, tudo bem, nosso foco agora é ensinar como fazer essa tarefa caso seja necessário, o porquê é apenas uma cereja no topo.